# -*- coding: utf-8 -*-
"""google/muril-base-cased.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3USzANIh7p0jeCupyg7fpdCvDNcph7M
"""

import pandas as pd
import os
import re

dataPath = "/content/youtube_comments_progress(1).csv"
df = pd.read_csv(dataPath)
df = df.dropna(subset=['text'])

# Define a function to clean the text
def preprocess_comment(comment):
    # Remove URLs
    comment = re.sub(r'http\S+|www\S+|https\S+', '', comment, flags=re.MULTILINE)
    # Remove mentions and hashtags
    comment = re.sub(r'\@\w+|\#', '', comment)
    # Lowercase the text
    comment = comment.lower()
    comment = re.sub(r'[^\w\s,]', '', comment)
    # Remove special characters and digits
    comment = re.sub(r'\W', ' ', comment)
    comment = re.sub(r'\d', '', comment)
    # Remove extra spaces
    comment = re.sub(r'\s+', ' ', comment).strip()
    return comment

# Apply the preprocessing function to the comments column
df['cleaned_comments'] = df['text'].apply(preprocess_comment).copy()

# View the cleaned comments
print(df['cleaned_comments'])

!pip install transformers -q
import pandas as pd
from transformers import pipeline
from tqdm import tqdm

# Load your dataset
df = pd.read_csv("/content/youtube_comments_progress(1).csv")
df = df.dropna(subset=['text'])

# Load zero-shot classifier
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Define candidate labels
candidate_labels = ["Positive", "Neutral", "Negative"]

# Run zero-shot classification
def get_sentiment_zero_shot(text):
    try:
        result = classifier(text, candidate_labels)
        return result["labels"][0]  # top prediction
    except:
        return "Unknown"

tqdm.pandas()
df["muril_sentiment_label"] = df["text"].progress_apply(get_sentiment_zero_shot)

# Save results
df.to_csv("hing_roberta_sentiment_output.csv", index=False)

import gc

try:
    df.to_csv("zero_shot_sentiment_progress.csv", index=False)
    print("✅ SAVED in the middle of execution!")
except Exception as e:
    print(f"❌ Couldn't save: {e}")

gc.collect()

from google.colab import files
files.download("zero_shot_sentiment_progress.csv")